# Site settings
title: Hello. I'm Mateusz
email: mateusz.kuzak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I work with scientists, computers and data.
  Currently eScience Research Engineer at Netherlands
  eScience Center, based in Amsterdam, the Netherlands.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://http://mkuzak.github.io/" # the base hostname & protocol for your site
twitter_username: matkuzak
github_username:  mkuzak

# Build settings
markdown: kramdown
