# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mateusz Kuzak
tagline:             'my digital home'
description:         'I work with scientists, computers and data. Curently <a href="https://www.esciencecenter.nl/team/escience-engineers">eScience Research Engineer</a> at <a href="https://www.esciencecenter.nl">Netherlands eScience Center</a>'
url:                 http://mkuzak.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mateusz Kuzak
  url:               https://twitter.com/matkuzak
  email:             mateusz.kuzak@gmail.com

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/mkuzak/mkuzak.github.io
